name: Run action

on:
  workflow_call:
    inputs:
      SHA:
        required: true
        type: string

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.SHA }}
      - name: Greet World
        id: hello
        uses: ./
        with:
          who-to-greet: "World"
      - name: Verify message
        run: echo "Message ${{ steps.hello.outputs.message }}"
